- Cargo.lock
- Cargo.toml
- src/amm/uniswap_v3/mod.rs
Addresses #96 
Patches a bug in tick increment/decrement in `simulate_swap` & `simulate_swap_mut`.
Adds more verbose swap sim testing. 
Bumps `uniswap_v3_math` to version `0.4.1` with `next_initialized_tick_within_one_word` patch.
> fix: v3 swap simulation

- Cargo.lock
- Cargo.toml
- README.md
- examples/discover-erc-4626-vaults.rs
- examples/discover-factories.rs
- examples/filter-value.rs
- examples/simulate-swap.rs
- examples/state-space.rs
- examples/swap-calldata.rs
- examples/sync-amms.rs
- src/amm/uniswap_v2/batch_request/mod.rs
- src/amm/uniswap_v2/factory.rs
- src/amm/uniswap_v2/mod.rs
- src/amm/uniswap_v3/batch_request/mod.rs
- src/amm/uniswap_v3/factory.rs
- src/amm/uniswap_v3/mod.rs
- src/discovery/erc_4626.rs
- src/discovery/factory.rs
- src/filters/value.rs
- src/state_space/state.rs
- src/sync/mod.rs
Example 1:
```
RUST_LOG=amms=info ETHEREUM_RPC_ENDPOINT=https://eth-mainnet.g.alchemy.com/v2/<key> cargo run --example discover-factories
```
```
2023-08-18T11:51:14.010291Z  INFO amms::discovery::factory: searching blocks 10000000-10049999
2023-08-18T11:51:14.387740Z  INFO amms::discovery::factory: discovered new factory address=0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f
2023-08-18T11:51:14.387827Z  INFO amms::discovery::factory: searching blocks 10050000-10099999
2023-08-18T11:51:14.816924Z  INFO amms::discovery::factory: searching blocks 10100000-10149999
2023-08-18T11:51:15.148548Z  INFO amms::discovery::factory: searching blocks 10150000-10199999
2023-08-18T11:51:15.410583Z  INFO amms::discovery::factory: discovered new factory address=0xbf85fdce9e4fa7d5a0177559150b15bf7f1bfd93 …
```
> Add basic top-level tracing, remove spinoff (WIP)

- src/sync/checkpoint.rs
- It's more correct
- It means that CLI argument parsing code that uses `PathBuf` can avoid having to convert to native string types
Rely on generic `P: AsRef<std::path::Path>`.
> Use `Path` for file paths in checkpoint sync

- Cargo.toml
- benches/uniswapv2_simulate.rs
Add benchmark for uniswapv2_simulate function
> Feat add uniswapv2_simulate benchmark

- src/amm/factory.rs
- src/amm/mod.rs
Problem:
Now, enum AMM (and Factory) compare be compared nor inserted into a HashMap. This is a bit inconvenient.
Solution:
I offer to implement Hash, Eq and PartialEq for AMM and Factory macros.
Moreover, I think it will be sufficient (to save up compute time) to just use Addresses for the comparison as they are unique Hashes a priori. 
P.S. Feel free to suggest a better idea. Always open for discussion :)
> Implement Hash, Eq and PartialEq for `AMM` and `Factory` 

- .cargo/config.toml
- benches/state_space.rs
- src/state_space/mod.rs
In benches module there was a "TODO" to add state change benchmarking tests, which I did.
Simple benchmarking tests added as in `state_change::tests` module.
Here's the results on my machine on `cargo bench` call:
```rust
test result: ok. 0 passed; 0 failed; 30 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running benches/state_space.rs (target/release/deps/state_space-eb8fcd7e36391f42)
Gnuplot not found, using plotters backend
add state changes benchmark
time:   [116.82 ns 116.88 ns 116.94 ns]
change: [-0.2926% -0.1940% -0.0996%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild
add empty state changes benchmark
time:   [96.076 ns 96.159 ns 96.270 ns]
change: [-0.5076% -0.3311% -0.1669%] (p = 0.00 < 0.05)
Change …
```
> add benchmarking tests as in state_changes module

- benches/state_space.rs
- examples/state-space.rs
- src/state_space/cache.rs
- src/state_space/error.rs
- src/state_space/mod.rs
This PR refactors the `StateSpaceCache` into a struct with it's own methods for adding/unwinding state changes. This PR also refactors parts of the `StateSpaceManager`.
> Improve `StateSpaceManager` and `StateSpaceCache`

- Cargo.toml
- src/lib.rs
This PR gates the state space mod behind the `state-space` feature flag. Additionally, the `filters` feature flag was removed and filters are now included by default.
> Fix compilation with `--no-default-features`

- src/discovery/factory.rs
- src/filters/value.rs
Addresses #196
This PR adds `BalancerV2Factory` to discoverable factories.
```rust
pub enum DiscoverableFactory {
UniswapV2Factory,
UniswapV3Factory,
BalancerV2Factory,
}
impl DiscoverableFactory {
pub fn discovery_event_signature(&self) -> B256 {
match self {
DiscoverableFactory::UniswapV2Factory => IUniswapV2Factory::PairCreated::SIGNATURE_HASH,
DiscoverableFactory::UniswapV3Factory => IUniswapV3Factory::PoolCreated::SIGNATURE_HASH,
DiscoverableFactory::BalancerV2Factory => IBFactory::LOG_NEW_POOL::SIGNATURE_HASH,
}
}
}
```
> feat(balancer): Add `BalancerV2Factory` to `discovery` mod

- Cargo.toml
- src/amm/balancer_v2/batch_request/mod.rs
- src/amm/balancer_v2/bmath.rs
- src/amm/balancer_v2/error.rs
- src/amm/balancer_v2/mod.rs
- src/amm/consts.rs
- src/amm/erc_4626/mod.rs
- src/amm/uniswap_v2/mod.rs
- src/errors.rs
- src/filters/value.rs
- Patches `simulate_swap` & `simulate_swap_mut`
- Better error handling in `bmath`
> feat(balancer): simulate_swap simulate_swap_mut

- Cargo.toml
- src/amm/uniswap_v2/mod.rs
- src/amm/uniswap_v3/batch_request/mod.rs
- src/amm/uniswap_v3/factory.rs
- src/amm/uniswap_v3/mod.rs
- src/state_space/cache.rs
- src/state_space/error.rs
- src/state_space/mod.rs
Changeset:
1. Alloy bumped to 0.3.
2. StateSpaceError updated to reflect the changes.
3. Type conversions across the repo to keep the same types after the update.
No functionality changed.
> Chore/alloy 0.3

- benches/uniswapv2_simulate.rs
- examples/filter-value.rs
- examples/simulate-swap.rs
- examples/swap-calldata.rs
- src/amm/uniswap_v2/factory.rs
- src/amm/uniswap_v2/mod.rs
- src/amm/uniswap_v3/factory.rs
- src/amm/uniswap_v3/mod.rs
A `factory_address` field in V2 and V3 proves helpful in understand what pools from which factories are discovered via the `PairCreated` / `PoolCreated` event. This can also prove helpful in analysing the contributions from which V2-like / V3-like protocols in pathing e.g 0x-style.
- Added `factory_address` to `UniswapV2Pool` and `UniswapV3Pool`
- Updated constructors
- Updated tests
> feat: v2 + v3 factory address tracked for better discovery debugging / analysis

- Cargo.toml
- src/amm/balancer_v2/batch_request/mod.rs
- src/amm/balancer_v2/mod.rs
- src/amm/erc_4626/batch_request/mod.rs
- src/amm/erc_4626/mod.rs
- src/amm/factory.rs
- src/amm/mod.rs
- src/amm/uniswap_v2/batch_request/mod.rs
- src/amm/uniswap_v2/factory.rs
- src/amm/uniswap_v2/mod.rs
- src/amm/uniswap_v3/batch_request/mod.rs
- src/amm/uniswap_v3/factory.rs
- src/amm/uniswap_v3/mod.rs
- src/errors.rs
- src/filters/value.rs
- src/state_space/error.rs
- src/sync/checkpoint.rs
- src/sync/mod.rs
Reworked decoding to a much more performant option via SolValue instead of DynSolValue.
Removed ".unwrap()".
Bumped deps.
Fixed logging verbosity for UniV2.
Yeeha!
> Perf(amms): Refine Decoding + Logging + Bump deps

- src/amms/uniswap_v2/mod.rs
- src/amms/uniswap_v3/mod.rs
This PR reintroduces the `swap_calldata()` function for all AMM variants included in the `0.7.0` release.
> feat(amms): Add `swap_calldata()` functions for `0.7.0` release

- src/amm/uniswap_v3/mod.rs
```
cargo run --example sync-amms
2024-08-25T01:47:36.740997Z  INFO amms::sync: Syncing AMMs step=500 factories=[UniswapV2Factory(UniswapV2Factory { address: 0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f, creation_block: 2638438, fee: 300 }), UniswapV2Factory(UniswapV2Factory { address: 0xc0aee478e3658e2610c5f7a4a2e1777ce9e4f2ac, creation_block: 10794229, fee: 300 }), UniswapV3Factory(UniswapV3Factory { address: 0x1f98431c8ad98523631ae4a59f267346ea31f984, creation_block: 185 })]
2024-08-25T01:47:36.741363Z  INFO amms::sync: Getting all AMMs from factory factory=UniswapV2Factory(UniswapV2Factory { address: 0xc0aee478e3658e2610c5f7a4a2e1777ce9e4f2ac, creation_block: 10794229, fee: 300 })
2024-08-25T01:47:36.741362Z  INFO amms::sync: Getting all AMMs from factory …
```
> fix panic: attempt to subtract with overflow

- Cargo.toml
- src/discovery/factory.rs
I have added a stream to process block logs asyncronously in discover_factories. I had to change some types and lifetimes and add some dependencies. I originally implemented this without using amms Factory and was a lot faster maybe i have messed sth up with the lifetimes.  I also did some implementations using fututres unordered but they did not seem to increase performance.
> Added async to discover factories

- src/amms/balancer/mod.rs
- src/amms/mod.rs
- src/amms/uniswap_v2/mod.rs
- src/amms/uniswap_v3/mod.rs
This PR introduces the `Token` type which encapsulates token addresses and decimals into a single struct. This change enforces that tokens have the same interface across all pools. In the future, this type could also optionally handle token tax logic.
Before:
```rust
pub struct UniswapV2Pool {
pub address: Address,
pub token_a: Address,
pub token_a_decimals: u8,
pub token_b: Address,
pub token_b_decimals: u8,
pub reserve_0: u128,
pub reserve_1: u128,
pub fee: usize,
}
```
After:
```rust
pub struct UniswapV2Pool {
pub address: Address,
pub token_a: Token,
pub token_b: Token,
pub reserve_0: u128,
pub reserve_1: u128,
pub fee: usize,
}
```
> feat(amms): Add `Token` type instead of specifying `token_address` and `token_decimals` directly on pool.

- contracts/test/WethValueInPoolsBatchRequest.t.sol
- src/state_space/filters/value.rs
When filtering by WETH value, all AMMs are filtered out.
This happens because the filter function provides the wrong PoolType value to the batch contract and causes the contract to return a WETH value of 0 for all pools.
There is a misalignment between:
```
enum PoolType {
Balancer,
UniswapV2,
UniswapV3
}
```
and:
```
let pool_type = match amm {
AMM::UniswapV2Pool(_) => 0,
AMM::UniswapV3Pool(_) => 1,
// TODO: At the moment, filters are not compatible with vaults or balancer pools
AMM::ERC4626Vault(_) => todo!(),
AMM::BalancerPool(_) => todo!(),
};
```
Bug report: https://github.com/darkforestry/amms-rs/issues/271
Align pool_type in the state space value filter with poolType enum in the contract.
Balancer was enabled for this filter because it's supported in the contract by `function …
> Fix: value filter filters out all AMMs due to misalignment with PoolType enum

- src/state_space/mod.rs
Subscribing to a StateSpaceManager caused errors on UniswapV3 Collect events due to incorrect filtering when only constructing with specified AMMs. This led to increased latency and crashes (if not caught properly). 
Added AMM specific filters in the sync function.
> Bugfix: Add amm events to filter

- src/state_space/mod.rs
The current filters for pools are added *post draining* becoming a no-op.
Create filters ahead of time.
> Bugfix: No-Op AMM Filter Sync

- Cargo.toml
- benches/erc_4626.rs
- benches/uniswap_v3.rs
ref #270 
This PR introduces benchmarks for `ERC4626Vault::simulate_swap()`
> chore(bench): add `simulate_swap` bench for ERC4626 vaults
